from __future__ import annotations

import json
import subprocess
import tempfile
import unittest
from pathlib import Path

from project_x_agent.worker import ProjectXWorker


class WorkerIntegrationTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary_directory = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary_directory.name)
        self.remote = self.root / "remote.git"
        self.repo = self.root / "repo"
        self.repo.mkdir()
        self._command("git", "init", "--bare", str(self.remote))
        self._git("init", "-b", "main")
        self._git("config", "user.name", "Project X Test")
        self._git("config", "user.email", "project-x-test@example.invalid")
        self._git("remote", "add", "origin", str(self.remote))
        (self.repo / "tasks").mkdir()
        (self.repo / "results").mkdir()
        (self.repo / "results" / "README.md").write_text("results\n", encoding="utf-8")
        (self.repo / ".gitignore").write_text("work/\n", encoding="utf-8")
        task = {
            "schema_version": 1,
            "id": "worker-test-001",
            "title": "Worker integration test",
            "objective": "Create the explicitly scoped test output.",
            "risk_level": "medium",
            "created_at": "2026-08-26T18:00:00+08:00",
            "authorization": {"execute": False},
            "execution": {
                "mode": "workspace-write",
                "write_paths": ["outputs/generated.txt"],
            },
            "metadata": {},
        }
        (self.repo / "tasks" / "worker-test.json").write_text(
            json.dumps(task), encoding="utf-8"
        )
        self._git("add", ".")
        self._git("commit", "-m", "seed")
        self._git("push", "-u", "origin", "main")
        self.fake_codex = self.root / "fake-codex"
        self.fake_codex.write_text(
            "#!/bin/sh\nmkdir -p outputs\nprintf 'generated by isolated fake codex\\n' > outputs/generated.txt\nprintf 'FAKE_CODEX_OK\\n'\n",
            encoding="utf-8",
        )
        self.fake_codex.chmod(0o700)

    def tearDown(self) -> None:
        self.temporary_directory.cleanup()

    def test_worker_executes_in_worktree_and_pushes_validated_files(self) -> None:
        outcome = ProjectXWorker(
            repo_root=self.repo, codex_binary=self.fake_codex
        ).run_once()

        self.assertEqual(outcome["status"], "completed")
        self.assertTrue(outcome["published"])
        self.assertEqual(
            self._remote_file("outputs/generated.txt"),
            "generated by isolated fake codex\n",
        )
        result = json.loads(self._remote_file("results/worker-test-001/result.json"))
        self.assertEqual(result["status"], "completed")
        self.assertEqual(result["executor"], "codex-cli")

    def _remote_file(self, path: str) -> str:
        return self._command(
            "git", "--git-dir", str(self.remote), "show", f"main:{path}"
        ).stdout

    def _git(self, *args: str) -> subprocess.CompletedProcess[str]:
        return self._command("git", "-C", str(self.repo), *args)

    @staticmethod
    def _command(*args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(args, text=True, capture_output=True, check=True)


if __name__ == "__main__":
    unittest.main()
